version: '3.7'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password --sort_buffer_size=4000000
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
