version: "3.7"
services:
  db:
    image: mysql:5.7
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
