service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline-scheduler
  - serverless-offline

functions:
  createSnapshot:
    handler: handlers/exportLogging.createSnapshot
    events:
      - schedule: cron(0 6 1/15 * ? *)
  exportSnapshot:
    handler: handlers/exportLogging.exportSnapshot
    events:
      - schedule: cron(10 6 1/15 * ? *)
  clearLogging:
    handler: handlers/exportLogging.clearLoggingTables
    events:
      - schedule: cron(20 6 1/15 * ? *)
