service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  rateHandler:
    handler: handlers/scheduled.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  secondFunction:
    handler: handlers/scheduled.run
    events:
      - schedule: rate(1 minute)
