service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline-scheduler
  - serverless-offline

functions:
  createSnapshot:
    handler: handlers/exportLogging.createSnapshot
    events:
      - schedule: cron(36 21 * * ? *)
      #- schedule: cron(5 6 1 * ? *) #12:05 AM MST on 1st day of each month
  exportSnapshot:
    handler: handlers/exportLogging.exportSnapshot
    events:
      - schedule: cron(46 21 * * ? *)
      #- schedule: cron(15 6 1 * ? *) #12:15 AM MST on 1st day of each month
  #clearLogging:
  #handler: handlers/exportLogging.clearLoggingTables
  #events:
  #- schedule: cron(10 21 * * ? *)
  #- schedule: cron(25 6 1 * ? *) #12:25 AM MST on 1st day of each month
