service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createSnapshot:
    handler: src/handlers/exportLogging.createSnapshot
    events:
      - schedule: rate(5 mins)
