service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createSnapshot:
    handler: handlers/scheduled.createSnapshot
    events:
      - schedule: cron(15 18 * * ? *)
  exportSnapshot:
    handler: handlers/scheduled.exportSnapshot
    events:
      - schedule: cron(25 18 * * ? *)
