service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-offline-scheduler
  - serverless-offline

functions:
  createSnapshot:
    handler: src/handlers/exportLogging.createSnapshot
    events:
      - schedule: cron(28 15 * * ? *)
      #- schedule: cron(5 6 1 * ? *) #12:05 AM MST on 1st day of each month
  exportSnapshot:
    handler: src/handlers/exportLogging.exportSnapshot
    events:
      #- schedule: cron(15 6 1 * ? *) #12:15 AM MST on 1st day of each month
      - schedule: cron(38 15 * * ? *)
