service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline-scheduler
  - serverless-offline

package:
  individually: true

functions:
  createSnapshot:
    handler: src/handlers/exportLogging.createSnapshot
    events:
      #- schedule: cron(5 6 1 * ? *) #12:05 AM MST on 1st day of each month
      - schedule: cron(55 21 * * ? *)
  exportSnapshot:
    handler: src/handlers/exportLogging.exportSnapshot
    events:
      #- schedule: cron(15 6 1 * ? *) #12:15 AM MST on 1st day of each month
      - schedule: cron(5 22 * * ? *)
  #clearLogging:
  #handler: src/handlers/exportLogging.clearLoggingTables
  #events:
  #- schedule: cron(19 15 * * ? *)
  #- schedule: cron(25 6 1 * ? *) #12:25 AM MST on 1st day of each month
