service: oareserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  rateHandler:
    handler: handlers/scheduled.exportSnapshotToS3
    events:
      - schedule: rate(10 minutes)
