# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Build Packages
        run: yarn build

      - name: Lint Files
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Run SQL Migrations
        run: yarn migrate:latest-prod
        env:
          OARE_DB_URL: ${{ secrets.OARE_DB_URL }}
        if: github.ref == 'refs/heads/master'

      - name: Zip Files
        run: yarn zip
        if: github.ref == 'refs/heads/master'

      # Uncomment if you want to debug a build. It will upload the zip file to S3.
      # The bucket does not have public access, so you'll need to change the access to public for this to work.
      # You'll also want to uncomment the if statement at the end of the zip action above
      # - name: Upload file to bucket
      #   uses: zdurham/s3-upload-github-action@master
      #   with:
      #     args: --acl public-read
      #   env:
      #     FILE: ./oare_build.zip
      #     AWS_REGION: "us-east-1"
      #     S3_BUCKET: ${{ secrets.AWS_BUCKET }}
      #     S3_KEY: ${{ secrets.S3_KEY }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
        if: github.ref == 'refs/heads/master'

      - name: Deploy Serverless to Lambda
        run: |
          yarn workspace @oare/serverless serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          yarn workspace @oare/serverless serverless deploy -v -r us-west-2
        if: github.ref == 'refs/heads/master'

      - name: Deploy to EB - US West (Oregon)
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: oare
          environment_name: oare-env-v2
          version_label: 'oare-oregon-${{ steps.time.outputs.time }}'
          region: us-west-2
          deployment_package: oare_build.zip
        if: github.ref == 'refs/heads/master'

      # NOTE: Temporarily Disabled While International Server(s) Are Deprecated
      # - name: Deploy to EB - Europe (Paris)
      #   uses: einaregilsson/beanstalk-deploy@v11
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: oare
      #     environment_name: oare-env-v2-europe
      #     version_label: 'oare-paris-${{ steps.time.outputs.time }}'
      #     region: eu-west-3
      #     deployment_package: oare_build.zip
      #   if: github.ref == 'refs/heads/master'
